<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-SD9UPUB" ignored="0" name="Test" tests="5" failures="3" timestamp="2021-10-28T23:15:06 CST" time="0.073" errors="0">
  <testcase name="test1" time="0.011" classname="demo.Demo"/>
  <testcase name="test2" time="0.002" classname="demo.Demo">
    <failure type="java.lang.AssertionError" message="expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at demo.Demo.test2(Demo.java:18)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.002" classname="demo.Demo"/>
  <testcase name="test4" time="0.001" classname="demo.Demo">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at demo.Demo.test4(Demo.java:28)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.001" classname="demo.Demo">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at demo.Demo.test5(Demo.java:33)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
</testsuite> <!-- Test -->
